import Link from "next/link";
import { ArrowRight, Apple, Monitor, ShieldAlert } from "lucide-react";
import { CopyCommand } from "@/components/copy-command";
import { PageHeading } from "@/components/dashboard-ui";
import { API_BASE_URL } from "@/lib/api";

const fileName = "SmartyAI-1.0.7-mac-arm64-internal.dmg";
const downloadUrl = "https://smartyai-downloads-807857683817.s3.ap-southeast-2.amazonaws.com/SmartyAI-1.0.7-mac-arm64-internal.dmg";
const windowsFileName = "SmartyAI-Setup-1.0.7-x64.exe";
const windowsDownloadUrl = `${API_BASE_URL}/api/downloads/latest/windows`;

export default function DashboardDownloadsPage() {
  return <><PageHeading eyebrow="Desktop app" title="Downloads" description="Install the latest SmartyAI test build for macOS or Windows." /><div className="grid max-w-4xl gap-px border border-white/10 bg-white/10 md:grid-cols-2"><a href={downloadUrl} download={fileName} className="bg-[#12120f] p-7"><Apple className="text-gold" size={22} /><h2 className="display-type mt-7 text-3xl font-semibold">SmartyAI 1.0.7</h2><p className="mt-2 text-xs text-[#777066]">macOS 13+ · Apple Silicon · 174 MB</p><span className="mt-6 flex items-center gap-2 text-xs font-bold text-gold">Download DMG <ArrowRight size={14} /></span></a><a href={windowsDownloadUrl} download={windowsFileName} className="bg-[#12120f] p-7"><Monitor className="text-[#7ed5d7]" size={22} /><h2 className="display-type mt-7 text-3xl font-semibold">SmartyAI 1.0.7</h2><p className="mt-2 text-xs text-[#777066]">Windows 10/11 · x64 installer</p><span className="mt-6 flex items-center gap-2 text-xs font-bold text-[#7ed5d7]">Download EXE <ArrowRight size={14} /></span></a></div><div className="grid max-w-4xl gap-px border-x border-b border-white/10 bg-white/10 md:grid-cols-2"><div className="bg-[#0d0d0b] p-7"><div className="flex gap-3"><ShieldAlert className="shrink-0 text-gold" size={19} /><div><h2 className="text-sm font-bold">Blocked by macOS?</h2><p className="mt-2 text-xs leading-5 text-[#777066]">First Control-click the app in Finder and choose Open. For this trusted, ad-hoc signed test build, use Terminal only if macOS still blocks it.</p></div></div><CopyCommand command="xattr -dr com.apple.quarantine /Applications/SmartyAI.app" /><CopyCommand command="open /Applications/SmartyAI.app" /></div><div className="bg-[#0d0d0b] p-7"><div className="flex gap-3"><ShieldAlert className="shrink-0 text-[#7ed5d7]" size={19} /><div><h2 className="text-sm font-bold">Windows SmartScreen</h2><p className="mt-2 text-xs leading-5 text-[#777066]">No quarantine command is needed. If prompted for this unsigned test build, choose More info and Run anyway. Never disable Windows Security.</p></div></div></div></div><div className="mt-5 max-w-4xl border border-white/10 p-5"><p className="text-sm font-bold">Platform support</p><p className="mt-2 text-xs leading-5 text-[#777066]">Windows includes overlay, AI chat, and offline system-audio transcription. Windows microphone transcription and screenshot OCR remain unavailable.</p><Link href="/windows" className="mt-4 inline-flex items-center gap-2 text-xs font-bold text-gold">Read Windows support details <ArrowRight size={14} /></Link></div></>;
}