export type MarketingPage = {
  title: string;
  eyebrow: string;
  description: string;
  intro: string;
  sections: { title: string; body: string; bullets?: string[] }[];
};

export const marketingPages: Record<string, MarketingPage> = {
  features: {
    title: "A clearer way to prepare for the live conversation.", eyebrow: "SmartyAI features", description: "Explore SmartyAI Response Studio, approved answer examples, desktop audio tools, and the multi-display overlay.", intro: "Build your own answer library before the interview, choose when audio or screen context is used, and keep guidance beside the conversation in a compact desktop workspace.",
    sections: [
      { title: "Save the answer you already know", body: "Teach AI lets you write, correct, and approve answer examples in Response Studio. When you need a prepared answer, open it from your library directly; displaying saved text does not make an AI request. New or related live questions still use AI, with approved examples available as guidance.", bullets: ["Your answer, in your words", "Open saved examples without generation latency", "Similar-question examples guide new responses"] },
      { title: "Hear both sides, with permission", body: "The desktop recording workflow can capture microphone and supported system audio as separate sources, then transcribe speaker-attributed turns. Recording requires an explicit start and participant consent. Audio capture and transcription support vary by operating system; Windows microphone transcription is not available in this release.", bullets: ["Candidate and interviewer audio kept distinct", "Visible recording state and consent step", "macOS has the broadest native transcription support"] },
      { title: "A compact overlay, under your control", body: "Keep SmartyAI beside your desktop workflow, move it between displays, and control microphone, system audio, and screen context explicitly. The app is identified as SmartyAI; it does not disguise itself as a system utility. Screen-share exclusion is best effort and varies by operating system and capture app.", bullets: ["Resize, reposition, and choose a toolbar layout", "Capture controls are user initiated", "Verify screen-share behavior in your setup"] },
      { title: "Fits beside the tools you already use", body: "SmartyAI is a desktop workspace, not a special integration with a particular interview platform. Keep the overlay beside supported meeting apps, browser calls, and coding screens, subject to your device permissions and sharing setup.", bullets: ["Video calls and browser meetings", "Coding assessments in a desktop browser", "Platform behavior depends on your OS and capture tool"] },
    ],
  },
  macos: {
    title: "Native context tools for macOS 13+.", eyebrow: "macOS support", description: "SmartyAI support for Whisper transcription, Apple Vision OCR, ScreenCaptureKit system audio, and desktop overlays on macOS 13+.", intro: "The macOS build contains the broadest local capture toolset in the current release. Permissions are requested from onboarding or a direct user action.",
    sections: [
      { title: "Included locally", body: "Bundled universal helpers support Intel and Apple Silicon Macs.", bullets: ["Offline Whisper microphone transcription", "Apple Vision screenshot OCR", "ScreenCaptureKit system-audio PCM capture", "Multi-display overlay and AI chat"] },
      { title: "Permissions stay visible", body: "Microphone and Screen Recording access must be granted in macOS settings. A restart may be required after Screen Recording permission changes." },
      { title: "Release status", body: "The 1.0.9 internal builds are ad-hoc signed and not Apple notarized. macOS may require a manual approval; public notarized distribution requires a Developer ID signature and Apple notarization." },
    ],
  },
  windows: {
    title: "Core overlay support, with clear limits.", eyebrow: "Windows support", description: "Current SmartyAI support and explicit limitations for Windows 10/11 x64.", intro: "Windows 10/11 x64 supports the Electron overlay, AI chat, encrypted local profile and grants, and capability-gated desktop actions.",
    sections: [
      { title: "Available now", body: "Use contextual AI chat and offline system-audio transcription in the multi-display overlay, with local data protected by Electron safeStorage and Windows DPAPI.", bullets: ["Overlay and AI chat", "Chromium/WASAPI loopback capture", "Bundled offline Whisper transcription", "Encrypted local context"] },
      { title: "Not available yet", body: "Windows microphone transcription and screenshot OCR do not have providers in this repository.", bullets: ["No Windows microphone transcription", "No Windows OCR"] },
      { title: "Capture behavior varies", body: "Best-effort capture exclusion depends on Windows and the capture application. SmartyAI does not promise undetectability." },
    ],
  },
  faq: {
    title: "Direct answers, no fine-print surprises.", eyebrow: "FAQ", description: "Frequently asked questions about SmartyAI desktop support, privacy, context, capture, and billing.", intro: "The short version: SmartyAI is a desktop assistant, macOS has the fullest native capture support, and plans use one-time Razorpay payments.",
    sections: [
      { title: "Is SmartyAI invisible on screen shares?", body: "No guarantee is possible. The desktop app uses best-effort capture exclusion, but results depend on the OS and the capture application." },
      { title: "Can I use resume and job context?", body: "SmartyAI can use context you provide to ground interview answers. Review the privacy notice and avoid sending sensitive information to any service until you have confirmed its data handling." },
      { title: "Does Windows support transcription or OCR?", body: "The current Windows release advertises offline transcription of captured system audio. Microphone transcription and screenshot OCR are not advertised as available in the current release. See the security page for platform and permission details." },
      { title: "Are job-application tools included with plans?", body: "No. Application automation is on the roadmap and is not included in today's checkout. Purchase for the interview and preparation tools currently available." },
      { title: "Does stopping a recording delete it?", body: "No. A completed recording session can retain media segments, transcripts, and events locally. Stopping capture and clearing the conversation are not account-wide deletion actions." },
      { title: "Does checkout auto-renew?", body: "No. Plan purchases are one-time Razorpay payments. Access ends after the selected duration unless you purchase again." },
      { title: "Where do AI provider keys live?", body: "Provider credentials stay in the server environment and are not shipped in frontend assets." },
    ],
  },
  contact: {
    title: "Talk to the people building it.", eyebrow: "Contact", description: "Contact SmartyAI for product support, security questions, and release access.", intro: "For account, release, or security questions, contact the team through the support channel configured by your SmartyAI distributor.",
    sections: [{ title: "What to include", body: "Share your platform, app version, the workflow you were using, and any non-sensitive error text. Never send passwords, JWTs, API keys, resumes, or private conversation content." }, { title: "Security reports", body: "Describe the affected component and reproduction steps without including active credentials or personal data." }],
  },
  privacy: {
    title: "Privacy starts with accurate boundaries.", eyebrow: "Privacy notice", description: "How SmartyAI handles interview context, account information, and permission-based capture.", intro: "Provide only information you are authorized to use. Review the service and platform permissions before enabling capture or sharing interview context.",
    sections: [{ title: "Interview context", body: "Resume, job description, and selected profile context can be saved on the desktop and synced to the backend. Relevant text can be included in requests to the configured AI provider. Do not submit credentials or information you are not authorized to use." }, { title: "Browser workspace", body: "The website workspace is a preview and may contact the configured service. Use sample information there; real-time audio and screen workflows belong in the desktop app." }, { title: "Desktop files and capture", body: "One-shot screenshot OCR and transcription run through local helpers; extracted text may be sent for an AI response. Full recording sessions can save media, transcripts, and events locally. Stopping a session does not delete saved files." }, { title: "Deletion boundaries", body: "Clearing a conversation removes its local copy, not necessarily saved recording sessions or backend profile data. No account-wide deletion or fixed retention period is promised here." }, { title: "Service policies", body: "Provider retention, backend backup retention, subprocessors, jurisdiction, and account-wide deletion require confirmation from the service operator before specific terms can be published. See the Security page for the known data flows." }],
  },
  terms: {
    title: "Terms that match the product today.", eyebrow: "Terms", description: "Current service terms foundation for SmartyAI development and pre-release access.", intro: "SmartyAI is currently offered as development or pre-release software unless your distributor provides separate signed terms.",
    sections: [{ title: "Appropriate use", body: "Use SmartyAI only where assistance and recording are permitted. You are responsible for participant consent, workplace rules, and applicable law. Review AI-generated answers before using them; no interview outcome is guaranteed." }, { title: "No guaranteed invisibility", body: "Capture exclusion is best effort. Do not rely on the product to be hidden from screen-sharing or monitoring software. Test the exact setup before an important call." }, { title: "Service availability", body: "Features may depend on platform permissions, native runtime availability, backend configuration, and third-party providers. Job-application automation is not included in today's checkout." }, { title: "Payments", body: "Plan access is activated after the backend verifies a one-time Razorpay payment. Purchases do not renew automatically." }],
  },
};

export const seoPages: Record<string, MarketingPage> = {
  "use-cases/interviews": { title: "Interview support that keeps you in the conversation.", eyebrow: "Use case", description: "Use resume and job-description context with a compact SmartyAI desktop overlay during interview preparation and important conversations.", intro: "Prepare your context in the desktop app, listen actively, and use suggestions as a structure for your own truthful experience.", sections: [{ title: "Before the conversation", body: "Add resume and job-description context locally, choose the display and overlay position, and grant only the capabilities you need." }, { title: "In the moment", body: "On macOS 13+, local transcription and screenshot OCR can provide context after explicit user actions. Windows supports typed context, system-audio capture, and offline transcription." }, { title: "Your experience stays yours", body: "Suggestions should help organize real examples, not fabricate credentials, achievements, or experience." }] },
    "alternatives/interview-assistants": { title: "Compare conversation assistants by their boundaries.", eyebrow: "Comparison notes", description: "Criteria for comparing interview assistants; verify every product claim with its publisher.", intro: "This page is illustrative, not an independently verified product comparison. Check current vendor documentation before making a decision.", sections: [{ title: "Ask where data lives", body: "Review each product's data handling before sharing personal information or interview context." }, { title: "Check platform parity", body: "Windows supports offline system-audio transcription but not microphone transcription or OCR." }, { title: "Reject absolute stealth claims", body: "Capture exclusion varies by operating system and capture tool and must not be treated as guaranteed invisibility." }] },
  "company/about": { title: "Software for staying thoughtful under pressure.", eyebrow: "About SmartyAI", description: "Learn the product principles behind SmartyAI's desktop conversation assistant.", intro: "SmartyAI is designed around a simple premise: real-time assistance should increase clarity without erasing consent, platform truth, or the user's own judgment.", sections: [{ title: "Build for the live moment", body: "Stable controls, readable answers, predictable shortcuts, and recoverable errors matter more than decorative novelty." }, { title: "Name the limits", body: "Platform gaps and capture uncertainty belong in product copy, not buried in release notes." }, { title: "Keep privilege narrow", body: "Desktop operations remain behind validated IPC, capability grants, and explicit user actions." }] },
};